# Generated by Django 6.0 on 2025-12-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo_path',
        ),
    ]
